spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create-drop